import '../styles/globals.css'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import Head from 'next/head'
config.autoAddCss = false

function MyApp ({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Ismael Martinez</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
