import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import Image from 'next/image'
import {
  faLanguage,
  faMoon,
  faUser,
  faHourglass,
  faCode,
  faEnvelope
} from "@fortawesome/free-solid-svg-icons"
import HeptagonLevelGraph from './Components/HeptagonLevelGraph'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ismael Martinez</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div className={styles.header}>
            <button className={styles.translate}> 
              <FontAwesomeIcon icon={faLanguage} />
            </button>
            <button className={styles.darkmode}>
              <FontAwesomeIcon icon={faMoon} />
              </button>
          </div>

          <div className={styles.presentation}>
            <div className={styles.presentationCard}>
              <span>
                <h1 className={styles.title}>Hi I&apos;m Elmais</h1>
                <p className={styles.subtitle}>Web Developer</p>
              </span>
              <div className={styles.circlePhoto}/>
            </div>
          </div>


          <div className={styles.linkers}>
            <a href='#profile' className={styles.link}>
              Perfil
              <FontAwesomeIcon icon={faUser}/>
            </a>
            <a href='#timeline' className={styles.link}>
              Línea de Tiempo
              <FontAwesomeIcon icon={faHourglass} />
            </a>
            <a href='#langs' className={styles.link}>
              Lenguajes
              <FontAwesomeIcon icon={faCode} />
            </a>
            <a href='#contact' className={styles.link}>
              Contacto
              <FontAwesomeIcon icon={faEnvelope} />
            </a>
          </div>

          <section>
            <div className={styles.profile} id='profile'>
              <Image alt='Avatar' src="/Avatar.svg" width={207} height={279}/>
              <div>
                <h2>Perfil</h2>
                <p>Experiencia trabajando en Desarrollo web como Full Stack Developer Jr y actualmente terminando la carrera de Ingeniería en Computación✏️</p>
                <p>Con especial afición por los lenguajes de programación JavaScript y Python ⌨️</p>
                <p>En mi tiempo trabajando⏳ logré aportar cambios a un proyecto de SAP (SIM APP PUSH) hecho en ReactJS en la parte Front-End y FastAPI/Python en la parte Back-End usando GraphQL y REST.</p>
                <p>Con ánimos de seguir aprendiendo y creciendo en este maravilloso mundo de la programación 🌐</p>
              </div>
            </div>
          </section>

          <section>
            <div className={styles.timeline} id='timeline'>
              <h2>Línea de Tiempo</h2>
              <div className={styles.timelineCard}></div>
            </div>
          </section>

          <section>
            <div className={styles.langs} id='langs'>
              <h2>Lenguajes</h2>
              <div className={styles.langsCard}>
               
               <HeptagonLevelGraph />
               
              </div>
            </div>
          </section>
        </div>
      </main>

    </div>
  ) 
}
